[package]
name = "mprovision"
version = "5.3.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]
edition = "2018"

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = true

[dependencies]
plist = "0.4"
chrono = "0.4"
memmem = "0.1"
futures = "0.1"
futures-cpupool = "0.1"
num_cpus = "1.8"
clap = "2" # structopt
structopt = "0.2"
dirs = "2.0"

[dev-dependencies]
expectest = "0.11"
tempdir = "0.3"

[profile.release]
panic = "abort"
lto = true
