[package]
name = "mprovision"
version = "1.0.1"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = true

[dependencies]
version = "2.0.1"
plist = "0.0.15"
chrono = "~0.2.0" # used in plist.
memmem = "0.1.1"
futures = "0.1.9"
futures-cpupool = "0.1.2"
num_cpus = "1.2.1"
clap = "2.20.0"

[dev-dependencies]
expectest = "0.6.0"
tempdir = "0.3.4"
