[package]
name = "mprovision"
version = "0.1.1"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"

[dependencies]
docopt = "0.6.78"
version = "2.0.1"
plist = "0.0.12"
chrono = "~0.2.0" # used in plist.

[dev-dependencies]
expectest = "0.4.1"
tempdir = "0.3.4"
