[package]
name = "mprovision"
version = "1.0.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = false

[dependencies]
docopt = "0.6.80"
version = "2.0.1"
plist = "0.0.13"
chrono = "~0.2.0" # used in plist.
crossbeam = "0.2.9"
rayon = "0.4.0"
memmem = "0.1.1"

[dev-dependencies]
expectest = "0.5.1"
tempdir = "0.3.4"
