[package]
name = "mprovision"
version = "1.0.1"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = false

[dependencies]
docopt = "0.6.86"
version = "2.0.1"
plist = "0.0.14"
chrono = "~0.2.0" # used in plist.
memmem = "0.1.1"
futures = "0.1.3"
futures-cpupool = "0.1.2"
num_cpus = "1.1.0"

[dev-dependencies]
expectest = "0.6.0"
tempdir = "0.3.4"
