[package]
name = "mprovision"
version = "3.1.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = true

[dependencies]
plist = "0.3"
chrono = "0.4"
memmem = "0.1.1"
futures = "0.1.17"
futures-cpupool = "0.1.8"
num_cpus = "1.8.0"
clap = "2" # structopt
structopt = "0.2.3"

[dev-dependencies]
expectest = "0.10"
tempdir = "0.3.5"

[profile.release]
panic = "abort"
lto = true
