[package]
name = "mprovision"
version = "6.3.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]
edition = "2021"

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = true

[dependencies]
plist = "1.2"
chrono = "0.4"
memmem = "0.1"
clap = "2" # structopt
structopt = "0.3"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.5"
main_error = "0.1"
colored = "2"

[dev-dependencies]
expectest = "0.12"
tempdir = "0.3"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
lto = true
