[package]
name = "mprovision"
version = "2.1.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = true

[dependencies]
plist = "0.1.3"
chrono = "0.2.25" # used in plist.
memmem = "0.1.1"
futures = "0.1.13"
futures-cpupool = "0.1.5"
num_cpus = "1.4.0"
clap = "2.23.3"

[dev-dependencies]
expectest = "0.7.0"
tempdir = "0.3.4"
