[package]
name = "mprovision-bin"
version = "0.1.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[[bin]]
name = "mprovision"

[dependencies]
mprovision = { path = "mprovision" }
docopt = "0.6.75"
