[package]
name = "mprovision"
version = "1.0.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = false

[dependencies]
docopt = "0.6.81"
version = "2.0.1"
plist = "0.0.13"
chrono = "~0.2.0" # used in plist.
memmem = "0.1.1"
futures = { git = "https://github.com/alexcrichton/futures-rs" }
futures-io = { git = "https://github.com/alexcrichton/futures-rs" }
futures-mio = { git = "https://github.com/alexcrichton/futures-rs" }
futures-cpupool = { git = "https://github.com/alexcrichton/futures-rs" }
num_cpus = "1.0.0"


[dev-dependencies]
expectest = "0.6.0"
tempdir = "0.3.4"
