[package]
name = "mprovision"
version = "6.0.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]
edition = "2018"

[[bin]]
path = "src/bin/main.rs"
name = "mprovision"
doc = false
test = true

[dependencies]
plist = "0.5"
chrono = "0.4"
memmem = "0.1"
clap = "2" # structopt
structopt = "0.3"
dirs = "2.0"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.3"

[dev-dependencies]
expectest = "0.12"
tempdir = "0.3"

[profile.release]
panic = "abort"
lto = true
